### PR TITLE
Execute _super prior to fetching data

### PR DESCRIPTION
**Pull request by nanojezra**
fixes bug where fetching /user/current is not added authorization header

### CODE REVIEW

**Comment by kpfefferle** [comment]
This should be fixed in #44 as I switched over to overriding `urlForQueryRecord` instead of `queryRecord` (I hope).

**Comment by nanojezra** [comment]
lamentably, the header property is still failing to be part of the query

**Comment by kpfefferle** [comment]
@nanojezra I'll look into it 👀

**Comment by nanojezra** [comment]
@kpfefferle I take back the comment. I was under the impression that the code had been pushed to master

**Comment by kpfefferle** [comment]
@nanojezra I still cleaned up the Adapter's headers code in #44

**Pull request closed without merging**
